---
# https://github.com/lycheeverse/lychee-action
# https://github.com/marketplace/actions/lychee-broken-link-checker
name: "Links (Fail Fast)"

permissions: read-all

on:
  # push:
  # pull_request:
  # repository_dispatch:
  # workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5"  # v4

      - name: "Link Checker"
        uses: "lycheeverse/lychee-action@7cd0af4c74a61395d455af97419279d86aafaede"  # v2.0.2
        with:
          fail: true
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
...
